--------------------------------------------------------
--  Fichier créé - jeudi-novembre-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"NUM_TELEPHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"DATE_INSCRIPTION" DATE, 
	"POINT_FIDELITE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NUM_TEL" NUMBER(8,0), 
	"POSTE" VARCHAR2(50 BYTE), 
	"LOGIN" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "FOURNISSEUR" 
   (	"ID_FOURNISSEUR" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"NUMERO_TELEPHONE" VARCHAR2(20 BYTE), 
	"CONDITION_PAIEMENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDONNANCE
--------------------------------------------------------

  CREATE TABLE "ORDONNANCE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"MEDECIN" VARCHAR2(100 BYTE), 
	"DATE_ORD" DATE, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"TYPE_PRODUIT" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER, 
	"PRIX" NUMBER(10,2), 
	"COULEUR" VARCHAR2(50 BYTE), 
	"EPAISSEUR" NUMBER(5,2), 
	"DIAMETRE" NUMBER(5,2), 
	"ID_FOURNISSEUR" NUMBER, 
	"ID_CLIENT" NUMBER, 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CLIENT
SET DEFINE OFF;
REM INSERTING into EMPLOYE
SET DEFINE OFF;
Insert into EMPLOYE (ID_EMPLOYE,NOM,PRENOM,ADRESSE,EMAIL,NUM_TEL,POSTE,LOGIN,PASSWORD) values ('2','ben fradj','nour','fefe"f"f''fé','fefe"f"f''fé','89456987','CEO','nour','1111');
Insert into EMPLOYE (ID_EMPLOYE,NOM,PRENOM,ADRESSE,EMAIL,NUM_TEL,POSTE,LOGIN,PASSWORD) values ('4','dazfezf','evqvd','egvererq@gmail','egvererq@gmail','12345678','RH','lo','7777');
Insert into EMPLOYE (ID_EMPLOYE,NOM,PRENOM,ADRESSE,EMAIL,NUM_TEL,POSTE,LOGIN,PASSWORD) values ('0','adem','vevezrv','feéf','feéf','85487945','RH',null,null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,PRENOM,ADRESSE,EMAIL,NUM_TEL,POSTE,LOGIN,PASSWORD) values ('1','jridi','amen','adefrvaerqv','adefrvaerqv','45478964','manager','amen','0000');
Insert into EMPLOYE (ID_EMPLOYE,NOM,PRENOM,ADRESSE,EMAIL,NUM_TEL,POSTE,LOGIN,PASSWORD) values ('3','miladi','hadil','miladi.hadil@esprit.tn','miladi.hadil@esprit.tn','94915801','manager','bahloula','4444');
REM INSERTING into FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into ORDONNANCE
SET DEFINE OFF;
REM INSERTING into PRODUIT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENT_PK" ON "CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE INDEX "EMPLOYE_PK" ON "EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_FOURNISSEUR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_FOURNISSEUR" 
BEFORE INSERT ON fournisseur
FOR EACH ROW
BEGIN
    :NEW.id_fournisseur := seq_fournisseur.NEXTVAL;
END;

/
ALTER TRIGGER "TRG_FOURNISSEUR" ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "PRODUIT" ADD PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "FOURNISSEUR" ADD PRIMARY KEY ("ID_FOURNISSEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDONNANCE
--------------------------------------------------------

  ALTER TABLE "ORDONNANCE" ADD PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ORDONNANCE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ORDONNANCE" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID_EMPLOYE") DEFERRABLE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMPLOYE" MODIFY ("POSTE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDONNANCE
--------------------------------------------------------

  ALTER TABLE "ORDONNANCE" ADD CONSTRAINT "FK_ORDONNANCE_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "PRODUIT" ADD CONSTRAINT "FK_PRODUIT_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CLIENT" ("ID_CLIENT") ENABLE;
  ALTER TABLE "PRODUIT" ADD CONSTRAINT "FK_PRODUIT_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "EMPLOYE" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "PRODUIT" ADD CONSTRAINT "FK_PRODUIT_FOURNISSEUR" FOREIGN KEY ("ID_FOURNISSEUR")
	  REFERENCES "FOURNISSEUR" ("ID_FOURNISSEUR") ENABLE;
